### PR TITLE
Dart 2 + strong mode

### PR DESCRIPTION
**Pull request by thosakwe**
Hello! Your package `dotenv` is used very often in the [Angel framework](https://angel-dart.github.io), so as the Dart SDK continues to evolve, for Angel to not be left behind, I have to send PR's to its dependencies to keep them up-to-speed.

That being said, the current iteration of `dotenv` is not compatible with Dart 2, so this PR provides the necessary fixes in a backwards-compatible way.

Please merge it when you have a chance.

P.S. Since the other open PR's involve breaking changes, I highly suggest that after my PR, you publish the current version as **1.0.0**, and then when the breaking changes land, publish a 2.0.0. This will help us limit the amount of sudden breakages due to Pub's strict enforcement of SemVer.

Thanks!!!

### CODE REVIEW

**Comment by mockturtl** [comment]
@thosakwe Thank you!  I was just reading your blog yesterday.

I'll land these changes and tag a release within the hour.  Let me know if any other changes would be helpful!

**Comment by mockturtl** [comment]
Merged.

**Comment by thosakwe** [comment]
Thanks for the merge! Really appreciate it.

**Comment by mockturtl** [comment]
@thosakwe Released.

**Pull request closed without merging**
